### ISSUE TITLE
Generated project files are kept around forever

### ISSUE THREAD

**Issue by tahini** [lttng/lttng-scope#77] opened 2018-04-05 16:44 UTC
My disk was almost full to start with and opening a few large traces filled the little space that was left. I had to explore my drive to guess the location of supplementary files in .local/share/lttng-scope

I know by design you keep supplementary files in case one opens the trace again. That's fine, but there should be a way to clean up.

Some suggestions (not exclusive):

* Document what to do in this case, if you get a NoSpaceLeftOnDevice exception, tell the user where to look for project files.

* When closing a trace, ask the user whether she wants to delete the analysis files or keep them for later

* Have a menu item to clear all files (except the current one of course)

* Have a menu item to see all saved projects and the amount of space they take and offer to delete them.

**Comment by alexmonthy** [comment] 2018-04-05 18:44
Hi Geneviève, thanks for the comments!

Indeed, right now there is not much done in terms of project/files management. We create database files for analyses and we just leave them there forever. It is an alpha after all ;)

The next version (0.4) which I am working on right now will include better project management and persistence. The idea would be to have the user work with "projects":
* A project would be a list of traces as well as any project-specific information the user defines, like project-specific configuration options, symbol definitions, filters, points-of-interests (bookmarks) etc.
* Initially one or several traces can be selected to serve as the base for a new project.
* The Save/Open actions would save to disk and re-open those projects.
* All extra analysis files that are created first go into a temporary directory.
* Upon closing, we can ask the user if they want to save the current project so it can be persisted and re-opened later. If they choose yes, we move the "temporary" files to the requested project-saving location. If they choose no we delete the generated files at this point.

This way at least, the only thing we would persist are things the user will have pointed to, so it becomes the user's responsibility afterwards.

**Comment by tahini** [comment] 2018-04-05 19:11
For now, you could simply document where the generated files are located so people like me who opened large traces just to try can delete them easily. Maybe in the limitations of the https://lttng.org/beta/ page. Because in the meantime, it's polluting the user's hard drive.

**Comment by alexmonthy** [comment] 2018-04-05 19:32
The reported problem is real, but it will be fixed by #51 so I will mark it as a duplicate of that one.

**Closed by alexmonthy** 2018-04-05 19:32 UTC
Labels: feature
